# Generated by Django 2.1.3 on 2019-03-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0014_auto_20190310_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='subject123',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='chapter123',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciscoapp.subject123'),
        ),
    ]
